### ISSUE TITLE
Support for SAMD M0 and M4

### ISSUE THREAD

**Issue by vslinuxdotnet** [rlogiacco/VoltageReference#10]
Hello,
Can you support ARM SAMD21(M0) and SAMD51(M4) ?
Thank You,
VS

**Comment by rlogiacco** [comment]
Sorry, I don’t have such devices and I’m not sure I would be able to do that: this library uses the hardware internal feature, I don’t know if those devices have such a feature. Why don’t you try to implement yourself and, if you find a way, I embed your code into the library?

**Comment by rlogiacco** [comment]
The OP never replied, closing
