### ISSUE TITLE
Example Sketch Is Wrong

### ISSUE THREAD

**Issue by anthonymonti2** [rlogiacco/VoltageReference#4]
I was using your library and testing it out with the AnalogAndVoltage example. When running the program the analog pin mv doesn't work because the analogRead is setting a variable of type int and then dividing by int. If you want a decimal point you won't get one. I changed it to a double and it worked

	double analog = analogRead(A0);
	int vcc = vRef.readVcc();
	Serial.print("Input voltage is ");
	Serial.print(vcc);
	Serial.print("mV, analog pin voltage is ");
	Serial.print(analog / 1023.0 * vcc);
	Serial.print("mV");
	Serial.println();
	delay(50);

**Comment by rlogiacco** [comment]
Thanks, it took me ages, but I got the time to apply your fix along with a little refactor, hopefully it will make usage clearer.
