### ISSUE TITLE
Using with ESP8266 board

### ISSUE THREAD

**Issue by patipol** [rlogiacco/VoltageReference#5]
Does this library could be used with ESP8266 boards like NodeMCU 1.0 (ESP-12E Module)?

For me, there are some errors while compiling:
> Arduino: 1.8.2 (Windows 8.1), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"
> 
> Build options changed, rebuilding all
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp: In member function 'uint16_t VoltageReference::readInternalRef()':
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:42:2: error: 'ADMUX' was not declared in this scope
> 
>   ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
> 
>   ^
> 
> In file included from C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:20:0:
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:42:14: error: 'REFS0' was not declared in this scope
> 
>   ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
> 
>               ^
> 
> C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
> 
>  #define _BV(b) (1UL << (b))
> 
>                          ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:42:27: error: 'MUX3' was not declared in this scope
> 
>   ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
> 
>                            ^
> 
> C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
> 
>  #define _BV(b) (1UL << (b))
> 
>                          ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:42:39: error: 'MUX2' was not declared in this scope
> 
>   ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
> 
>                                        ^
> 
> C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
> 
>  #define _BV(b) (1UL << (b))
> 
>                          ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:42:51: error: 'MUX1' was not declared in this scope
> 
>   ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
> 
>                                                    ^
> 
> C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
> 
>  #define _BV(b) (1UL << (b))
> 
>                          ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:46:2: error: 'ADCSRA' was not declared in this scope
> 
>   ADCSRA |= _BV(ADSC); // Start conversion
> 
>   ^
> 
> In file included from C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:20:0:
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:46:16: error: 'ADSC' was not declared in this scope
> 
>   ADCSRA |= _BV(ADSC); // Start conversion
> 
>                 ^
> 
> C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
> 
>  #define _BV(b) (1UL << (b))
> 
>                          ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:47:32: error: 'bit_is_set' was not declared in this scope
> 
>   while (bit_is_set(ADCSRA, ADSC)); // measuring
> 
>                                 ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:48:16: error: 'ADCL' was not declared in this scope
> 
>   uint8_t low = ADCL; // must read ADCL first - it then locks ADCH
> 
>                 ^
> 
> C:\Users\admin\Documents\Arduino\libraries\Voltage_Reference\VoltageReference.cpp:49:17: error: 'ADCH' was not declared in this scope
> 
>   uint8_t high = ADCH; // unlocks both
> 
>                  ^
> 
> exit status 1
> Error compiling for board NodeMCU 1.0 (ESP-12E Module).
> 
> This report would have more information with
> "Show verbose output during compilation"
> option enabled in File -> Preferences.

Support ESP8266 board would be appriciated.

**Comment by rlogiacco** [comment]
The library uses Atmel MCU specific registries and features, meaning it's **NOT** compatible with any other MCU without heavy customization.

> Support ESP8266 board would be appriciated.

You are welcome to contribute it

**Comment by patipol** [comment]
Thank you very much for your reply. It's very difficult for me to contribute it since I'm very newbie in this field, my question indicated that.

**Comment by rlogiacco** [comment]
We have all been newbies once. It has been the necessity to solve an issue to push us learn new stuff: if you'll learn how to do this same thing on ESP8266 I will be happy to accept your contribution.
As this is not a problem I am facing I have no need to fix it, meaning I'm not going to learn how to do it myself.
