### ISSUE TITLE
Calculated input voltage not providing calibration value

### ISSUE THREAD

**Issue by cuteboi** [rlogiacco/VoltageReference#6]
I tried this out on an Arduino Uno - Mega328p

```
--- MENU ---
	R to read Vcc
	L to load calibration from EEPROM
	S to store calibration into EEPROM
	C to clear calibration from EEPROM
	dddd (4 digits) to calibrate for mV
	A to print EEPROM calibration start address (length 3)
	Adddd (4 digits) to set EEPROM calibration start address (length 3)
	H prints this help
Calculated input voltage is 5120mV
Real bandgap voltage is 1101mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
```
Sending R again to the serial again, presented me with 0mv for everything

```
Calculated input voltage is 0mV
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
```

Ideas? The code looks correct, and works when using the readVCC() from the secret multimeter.

**Comment by rlogiacco** [comment]
That's expected behaviour: you tried to calibrate your arduino to 0... Once you calibrate for a 0 bandgap voltage everything is 0 because any value multiplied by zero is... guess?
You must reset your board to return to a non zero reference, then calibrate to some value corresponding to whatever you read on your multimeter (like `5000` if you read exactly 5.00V, `4550` if it says 4.55V, etc).
If the [calibration instructions](https://github.com/rlogiacco/VoltageReference#calibration) aren't clear I'm willing to hear any suggestion.

BTW, what do you mean by _secret multimeter_?

**Comment by cuteboi** [comment]
I was talking about [Scott Daniel's Work](https://provideyourown.com/2012/secret-arduino-voltmeter-measure-battery-voltage/), which is called Secret Arduino Voltmeter.

Maybe my reading comprehension went out the window, I can understand what you mean with more context.  I was under the impression that 'read VCC" meant to just read the information on the system, and just the VCC, and I was expecting it to return the same values until I specified a calibration with dddd or Adddd.  Since I only did R, I didn't expect it would be setting the calibration at any time. I'll try and get more rest, maybe comprehension on my behalf is really needed.

I think leave this closed, maybe I'll just supply a PR when I ask my friend to try it out, and see if it was expected behavior.

**Comment by rlogiacco** [comment]
That is correct indeed: if you never sent a `0` then there's something wrong with the calibration sketch.

Can you please double check? You should be able to send as many `R` (or any other command) as you wish and nothing should change unless you send a series of four digits.

Actually, I noticed a potential issue: the sketch might badly interpret non-alphanumeric characters and then try to interpret those as numeric.

This `else` statement would probably be more reliable refactored to ` else if (isdigit(c))`
https://github.com/rlogiacco/VoltageReference/blob/b080350eb7c9731be625d82ef8d076105ce0936c/examples/EEPROMCalibration/EEPROMCalibration.ino#L107

**Comment by cuteboi** [comment]
```
--- MENU ---
	R to read Vcc
	L to load calibration from EEPROM
	S to store calibration into EEPROM
	C to clear calibration from EEPROM
	dddd (4 digits) to calibrate for mV
	A to print EEPROM calibration start address (length 3)
	Adddd (4 digits) to set EEPROM calibration start address (length 3)
	H prints this help
82
Calculated input voltage is 5120mV
Real bandgap voltage is 1101mV
13
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
10
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
```

Yup, it's the else, it's not seeing the character, so it assumes it's a number, when it's in fact a carriage return and line feed.  I ended up doing a:

```
  char c = Serial.read();

  Serial.println( (int) c);
  ```

And it showed those integers

I swapped that last ` } else  { ` with ` 	} else if (isdigit(c)) { ` and I no longer see the issue.

```
--- MENU ---
	R to read Vcc
	L to load calibration from EEPROM
	S to store calibration into EEPROM
	C to clear calibration from EEPROM
	dddd (4 digits) to calibrate for mV
	A to print EEPROM calibration start address (length 3)
	Adddd (4 digits) to set EEPROM calibration start address (length 3)
	H prints this help
82
Calculated input voltage is 5120mV
Real bandgap voltage is 1101mV
13
10
```
