### ISSUE TITLE
Memory usage is rather high for a small application

### ISSUE THREAD

**Issue by cuteboi** [rlogiacco/VoltageReference#8]
I noticed that memory usage is about 41% on the Arduino Uno for the EEPROMCalibration app.  I think it's rather high.

**Comment by rlogiacco** [comment]
Well, those sketches are not meant to be used for production purposes, the calibration one in particular...
I'm not sure adding `F()` to the examples would help the library because that is a function non-portable outside of the Arduino world (I'm thinking to ESP8266, Teensy and similar).

**Comment by cuteboi** [comment]
Understood, just felt that it used a lot, and plenty of people copy and paste code quite often.  And having best practices on Arduino frameworks/Atmel platforms is a good idea.  Yeah, it's not applicable to ESP8266, but at least those ESP/ARM uC respect const datatypes.

Welp, close this, if it's not needed.  Thanks for reading and responding, I appreciate that.
